// s160 2026-09-24 — generated by /root/jb_lint_batch.py (one builder for every npm linter).
plugins { id("java"); id("org.jetbrains.intellij.platform") version "2.2.1" }
group = "com.getreadystack"; version = "1.0.0"
repositories { mavenCentral(); intellijPlatform { defaultRepositories() } }
dependencies { intellijPlatform { intellijIdeaCommunity("2024.2.4") } }
java { toolchain { languageVersion = JavaLanguageVersion.of(17) } }
intellijPlatform {
  pluginConfiguration { ideaVersion { sinceBuild = "242"; untilBuild = provider { null } } }
  buildSearchableOptions = false
}
