// s160 2026-09-24 — generated by /root/jb_lint_batch.py · s175 2026-10-01 hand-built (pure-Java engine + Java map + report) — jb_lint_batch skips it (.hand_built)
plugins { id("java"); id("org.jetbrains.intellij.platform") version "2.2.1" }
group = "com.getreadystack"; version = "1.1.0"
repositories { mavenCentral(); intellijPlatform { defaultRepositories() } }
dependencies { intellijPlatform { intellijIdeaCommunity("2024.2.4") } }
java { toolchain { languageVersion = JavaLanguageVersion.of(17) } }
intellijPlatform {
  pluginConfiguration { ideaVersion { sinceBuild = "242"; untilBuild = provider { null } } }
  buildSearchableOptions = false
}
