// GENERATED by /root/_audit_s175/f4_jb_oracle/gen.py - do not edit by hand.
package com.getreadystack.p_oracle_jdk_license_gate;

final class Txt {
  static final String VERSION = "1.1.0";
  static final String SLUG = "oracle-jdk-license-gate";
  static final String TITLE = "Oracle JDK License Gate";
  static final String BUY_URL = "https://getreadystack.com/api/buy/cl/polar_cl_0qxUalAkf4ad9kwGZmCwgbKANSqawgoJq6rVf2ZeWRh";
  static final String TEAM_URL = "https://getreadystack.com/api/buy/cl/polar_cl_l6iN1uWt0FwWu7tBsczD0jWpP2vxFM54Wdwqb3KPi1G";
  static final String PRICE = "29";
  static final String STAKE_SOURCE = "Oracle Java SE Universal Subscription Global Price List";
  static final String STAKE_URL = "https://www.oracle.com/a/ocom/docs/corporate/pricing/java-se-subscription-pricelist-5028356.pdf";
  static final String[] LANGS = {"en", "de", "ja", "es", "pt"};
  /** per language: {offer with pins, offer without pins, "Show the Java map", "Not now"} - from javamap.js T */
  static final String[][] MAP = {
    {"{t}: {n} place{s} in this project choose a Java build ({sum}). Oracle-licensed today: {m}. See each line and the free Temurin line for it.", "{t}: this is a Java project, but no file here pins a Java vendor. See which JDK this machine runs it on and the Temurin line for each place.", "Show the Java map", "Not now"},
    {"{t}: {n} Stelle(n) in diesem Arbeitsbereich w\u00e4hlen einen Java-Build ({sum}). Heute unter Oracle-Lizenz: {m}. Jede Zeile und die freie Temurin-Zeile dazu ansehen.", "{t}: Das ist ein Java-Projekt, aber keine Datei legt hier einen Java-Anbieter fest. Ansehen, mit welchem JDK dieser Rechner es ausf\u00fchrt, und die Temurin-Zeile f\u00fcr jede Stelle.", "Java-\u00dcbersicht zeigen", "Sp\u00e4ter"},
    {"{t}: \u3053\u306e\u30ef\u30fc\u30af\u30b9\u30da\u30fc\u30b9\u306b\u306f Java \u30d3\u30eb\u30c9\u3092\u9078\u3076\u7b87\u6240\u304c {n} \u304b\u6240\u3042\u308a\u307e\u3059 ({sum})\u3002\u672c\u65e5\u6642\u70b9\u3067 Oracle \u30e9\u30a4\u30bb\u30f3\u30b9\u306e\u3082\u306e: {m}\u3002\u5404\u884c\u3068\u3001\u7f6e\u304d\u63db\u3048\u3089\u308c\u308b Temurin \u306e\u884c\u3092\u78ba\u8a8d\u3067\u304d\u307e\u3059\u3002", "{t}: Java \u30d7\u30ed\u30b8\u30a7\u30af\u30c8\u3067\u3059\u304c\u3001Java \u306e\u30d9\u30f3\u30c0\u30fc\u3092\u6307\u5b9a\u3057\u3066\u3044\u308b\u30d5\u30a1\u30a4\u30eb\u304c\u3042\u308a\u307e\u305b\u3093\u3002\u3053\u306e\u30de\u30b7\u30f3\u304c\u3069\u306e JDK \u3067\u5b9f\u884c\u3057\u3066\u3044\u308b\u304b\u3068\u3001\u5404\u7b87\u6240\u306e Temurin \u306e\u884c\u3092\u78ba\u8a8d\u3067\u304d\u307e\u3059\u3002", "Java \u30de\u30c3\u30d7\u3092\u8868\u793a", "\u5f8c\u3067"},
    {"{t}: {n} lugar(es) de este espacio de trabajo eligen una build de Java ({sum}). Con licencia de Oracle hoy: {m}. Mira cada l\u00ednea y la l\u00ednea gratuita de Temurin que la sustituye.", "{t}: es un proyecto Java, pero ning\u00fan archivo fija aqu\u00ed un proveedor de Java. Mira con qu\u00e9 JDK lo ejecuta esta m\u00e1quina y la l\u00ednea de Temurin para cada lugar.", "Mostrar el mapa de Java", "Ahora no"},
    {"{t}: {n} lugar(es) deste workspace escolhem uma build de Java ({sum}). Com licen\u00e7a da Oracle hoje: {m}. Veja cada linha e a linha gratuita do Temurin que a substitui.", "{t}: este \u00e9 um projeto Java, mas nenhum arquivo fixa aqui um fornecedor de Java. Veja com qual JDK esta m\u00e1quina o executa e a linha do Temurin para cada lugar.", "Mostrar o mapa de Java", "Agora n\u00e3o"}
  };
  /** per language: {team line, team button} - the s174 clean-result team offer */
  static final String[][] TEAM = {
    {"Using this across a team? One team key ($149 once, 5 seats) unlocks the dated report in every repository you open, for every ReadyStack linter.", "Team key \u2014 $149 once, 5 seats"},
    {"Im Team im Einsatz? Ein Team-Schl\u00fcssel ($149 einmalig, 5 Pl\u00e4tze) schaltet den datierten Bericht in jedem ge\u00f6ffneten Repository frei, f\u00fcr alle ReadyStack-Linter.", "Team-Schl\u00fcssel \u2014 $149 einmalig, 5 Pl\u00e4tze"},
    {"\u30c1\u30fc\u30e0\u3067\u4f7f\u3044\u307e\u3059\u304b\uff1f\u30c1\u30fc\u30e0\u30ad\u30fc 1 \u3064\uff08$149 \u8cb7\u3044\u5207\u308a\u30fb5 \u5e2d\uff09\u3067\u3001\u958b\u3044\u305f\u3059\u3079\u3066\u306e\u30ea\u30dd\u30b8\u30c8\u30ea\u3067\u65e5\u4ed8\u5165\u308a\u30ec\u30dd\u30fc\u30c8\u304c\u4f7f\u3048\u3001ReadyStack \u306e\u5168\u30ea\u30f3\u30bf\u30fc\u304c\u5bfe\u8c61\u3067\u3059\u3002", "\u30c1\u30fc\u30e0\u30ad\u30fc \u2014 $149 \u8cb7\u3044\u5207\u308a\u30fb5 \u5e2d"},
    {"\u00bfLo usa un equipo? Una clave de equipo ($149 pago \u00fanico, 5 puestos) desbloquea el informe fechado en cada repositorio que abra, para todos los linters de ReadyStack.", "Clave de equipo \u2014 $149 pago \u00fanico, 5 puestos"},
    {"Usa em equipe? Uma chave de equipe (US$ 149, pagamento \u00fanico, 5 lugares) libera o relat\u00f3rio datado em todo reposit\u00f3rio que voc\u00ea abrir, para todos os linters da ReadyStack.", "Chave de equipe \u2014 US$ 149 uma vez, 5 lugares"}
  };
  /** per language: the company line on a clean result - stake.json clean_line, 500 people = $90,000 a year at Oracle list price */
  static final String[] CLEAN = {"Oracle prices Java SE by total headcount, not by install: one Oracle build in any other repository puts the whole payroll in scope - at list price a 500-person company pays $90,000 a year.", "Oracle berechnet Java SE nach der gesamten Belegschaft, nicht pro Installation: ein einziger Oracle-Build in einem anderen Repository bringt die ganze Belegschaft in die Rechnung - zum Listenpreis zahlt ein Unternehmen mit 500 Personen $90,000 pro Jahr.", "Oracle \u306f Java SE \u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u6570\u3067\u306f\u306a\u304f\u5168\u5f93\u696d\u54e1\u6570\u3067\u8ab2\u91d1\u3057\u307e\u3059\u3002\u307b\u304b\u306e\u3069\u3053\u304b\u306e\u30ea\u30dd\u30b8\u30c8\u30ea\u306b Oracle \u30d3\u30eb\u30c9\u304c 1 \u3064\u3042\u308c\u3070\u5168\u5f93\u696d\u54e1\u304c\u5bfe\u8c61\u3067\u3059\u3002\u5b9a\u4fa1\u3067\u306f 500 \u4eba\u306e\u4f1a\u793e\u3067\u5e74 $90,000 \u3067\u3059\u3002", "Oracle cobra Java SE por toda la plantilla, no por instalaci\u00f3n: una sola build de Oracle en cualquier otro repositorio pone a toda la plantilla en la cuenta; a precio de lista, una empresa de 500 personas paga $90,000 al a\u00f1o.", "A Oracle cobra o Java SE pelo quadro inteiro, n\u00e3o por instala\u00e7\u00e3o: uma \u00fanica build da Oracle em qualquer outro reposit\u00f3rio coloca todo o quadro na conta; a pre\u00e7o de tabela, uma empresa de 500 pessoas paga US$90,000 por ano."};
  static int li(String lang) { for (int i = 0; i < LANGS.length; i++) if (LANGS[i].equals(lang)) return i; return 0; }
  private Txt() { }
}
