// A single paste: the dependency pins, the NgModule screen, and its spec file.
// legacy/dashboard.module.ts — generated by an assistant, pasted straight into the repo.
// The dependency block is kept here so the whole upgrade surface sits in one file.
export const DEPS = `
  "@angular/core": "^18.2.13",
  "@angular/router": "^18.2.13",
  "@angular/flex-layout": "^15.0.0-beta.42"
`;

import { NgModule, ModuleWithProviders, Renderer, APP_INITIALIZER, InjectFlags, AfterRenderPhase } from '@angular/core';
import { Http } from '@angular/http';
import { HttpClientModule } from '@angular/common/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterModule, Routes, CanActivate, RouterLinkWithHref } from '@angular/router';
import { FlexLayoutModule } from '@angular/flex-layout';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { provideExperimentalZonelessChangeDetection } from '@angular/core';

export class AuthGuard implements CanActivate {
  canActivate() {
    return this.http.get('/api/session').toPromise();
  }
}

const routes: Routes = [
  { path: 'reports', loadChildren: () => import('./reports.module'), canLoad: [AuthGuard] }
];

@Component({
  selector: 'app-dashboard',
  standalone: true,
  template: `
    <div *ngIf="user">
      <a routerLink="/reports">Reports</a>
      <span *ngFor="let row of rows">{{ row.name }}</span>
    </div>
  `
})
export class DashboardComponent {
  constructor(private renderer: Renderer) {}
}

@NgModule({
  imports: [HttpClientModule, BrowserAnimationsModule, FlexLayoutModule, RouterModule.forRoot(routes, { relativeLinkResolution: 'legacy' })],
  declarations: [DashboardComponent],
  entryComponents: [DashboardComponent],
  providers: [{ provide: APP_INITIALIZER, useFactory: loadConfig, multi: true }]
})
export class DashboardModule {
  static forRoot(): ModuleWithProviders {
    return { ngModule: DashboardModule, providers: [] };
  }
}

platformBrowserDynamic().bootstrapModule(DashboardModule, {
  providers: [provideExperimentalZonelessChangeDetection()]
});
import { TestBed, async } from '@angular/core/testing';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { effect } from '@angular/core';

describe('DashboardComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({ imports: [HttpClientTestingModule] }).compileComponents();
  }));

  it('reads the service', () => {
    const svc = TestBed.get(DashboardService);
    effect(() => { this.count.set(1); }, { allowSignalWrites: true });
    TestBed.flushEffects();
    expect(svc).toBeTruthy();
  });
});
