"""Checkout tests — generated by an assistant, last touched before the pytest 8 bump."""
import unittest
import warnings

import pytest

from shop.checkout import Cart, apply_coupon, CouponError


@pytest.yield_fixture
def cart():
    c = Cart(currency="EUR")
    yield c
    c.close()


@pytest.mark.skipif(not pytest.config.getoption("--slow"), reason="slow")
@pytest.fixture
def big_cart(cart):
    for i in range(500):
        cart.add(f"sku-{i}", 1)
    return cart


def setup(self):
    self.seen = []


def test_writes_receipt(cart, tmpdir):
    path = tmpdir.join("receipt.txt")
    cart.add("sku-1", 2)
    cart.write_receipt(str(path))
    assert path.read().startswith("RECEIPT")


def test_expired_coupon_warns(cart):
    with pytest.warns(None) as record:
        apply_coupon(cart, "SUMMER2024")
    assert len(record) == 1


def test_unknown_coupon(cart):
    with pytest.raises(CouponError, message="coupon should be rejected"):
        apply_coupon(cart, "NOPE")


def test_skips_without_backend(cart):
    if not cart.backend_available():
        pytest.skip(msg="no payment backend in this environment")


async def test_async_totals(cart):
    cart.add("sku-9", 3)
    total = await cart.total_async()
    assert total == 3


@pytest.fixture
def event_loop():
    import asyncio
    loop = asyncio.new_event_loop()
    yield loop
    loop.close()


class TestRefunds(unittest.TestCase):
    @pytest.mark.parametrize("amount,expected", [(10, 10), (0, 0)])
    def test_refund_amounts(self, amount, expected):
        self.assertEqual(Cart(currency="EUR").refund(amount), expected)


def pytest_collection_modifyitems(items):
    for item in items:
        if item.get_marker("slow"):
            item.add_marker(pytest.mark.skip(reason="slow"))
